src/components/Card/styles.scss, src/constants/colors.scss
- Remove hardcoded colour values and replace card .hover css
- Add animated hover transition
=> Improve hover

guides.json
=> Add APA citation style

src/components/TodayView/index.tsx, src/screens/calendar.tsx, yarn.lock
- Fix issue where events will be reported wrongly on the last day of the event
- Add special text on the last day of vacation / recess
- Remove logging
=> Incorrect Date Handling

README.md, package.json, src/components/CardLink.tsx, src/components/NavBar.tsx, src/components/Ticker.tsx
- update LKS library count to match the current library rules
- fix icon size when moved to next.js
- fix links in README after next.js move
=> chore: update library count and design

package.json, src/components/Card/AppLibrary/components/App.tsx, src/components/Card/AppLibrary/components/Section.tsx, src/components/Card/Widget/Capacity/components/CapacityRow.tsx, src/components/Card/Widget/Capacity/index.tsx, src/components/Card/Widget/TodayCard/components/CalendarEvents.tsx, src/components/Card/Widget/TodayCard/components/LoadingCalendar.tsx, src/components/Card/Widget/TodayCard/components/LoadingToday.tsx, src/components/Card/Widget/TodayCard/components/TodayEvent.tsx, src/components/Modal/BOSSTimetable/index.tsx, src/pages/_document.tsx, yarn.lock
* feat: show loading when fetching data
* feat: show number of events the next day when TodayEvents has nothing to show
* refactor: open apps in new tab
* refactor: mobile responsiveness
=> feat: loading animation

public/data/apps.json, src/components/Card/Calendar/components/EventsSection.tsx, src/components/Card/Widget/TodayCard/components/CalendarEvents.tsx, src/components/Header/index.tsx, src/pages/index.tsx, src/theme.ts, types/styled.d.ts
* refactor: show better feedback when no events are found for that certain day
* refactor: show more title and subtitle of calendar event
* fix: wrong link type for welcome-guide
=> refactor: improve calendar experience

src/components/Card/AppLibrary/components/App.tsx, src/components/Card/AppLibrary/index.tsx, src/components/Header/index.tsx, src/components/Navigation/index.tsx, src/contexts/utils/getCurrentEvent.ts, src/layouts/DefaultLayout.tsx, src/pages/calendar.tsx, src/pages/index.tsx, src/theme.ts, types/styled.d.ts
* fix: incorrect date validation to determine last day of calendar event
* refactor: improve mobile optimisations
* uninterrupted scrolling on mobile
* show Header only on mobile 
* concat app descriptions to two lines
=> fix: crash on event last day

public/data/apps.json, src/Schema.ts, src/components/Card/AppLibrary/components/App.tsx, src/components/Card/AppLibrary/components/Section.tsx, src/components/Card/AppLibrary/index.tsx, src/components/Modal/Home/AddHomeScreen.tsx, src/components/Modal/styled.tsx, src/layouts/DefaultLayout.tsx, src/pages/calendar.tsx, src/pages/index.tsx, src/theme.ts, types/styled.d.ts
* scrollable title
* much larger hit area for apps
* background image fix
=> feat: new app library design

src/components/Card/Calendar/components/CalendarRow.tsx, src/contexts/utils/sortEventsByDate.ts
#41
* missing important dates due to validation check
* case validation fail to check for dates between midnight and the next midnight
=> fix: missing important dates

public/data/apps.json, src/components/Card/Widget/TodayCard/components/CalendarEvents.tsx, src/utils/schoolGuide/softwareLinks.tsx
* refactor: update list of apps shortcuts
* remove apps which fails to uphold their use
* add SMUSA feedback url
* refactor: add more productivity apps to School Guides
* change Note-Taking title to Productivity
* add more productivity apps
=> refactor: update list of apps

src/components/Card/Widget/Capacity/index.tsx
Issue #61 
Due to SMU updated covid-19 protocols, libraries now have higher capacities. This PR aims to update the max capacity numbers
=> fix: Update library capacity number #61

src/components/Card/Widget/TodayCard/components/TodayEvent.tsx, src/contexts/DataContext.tsx, src/pages/calendar.tsx
This PR removes comments and console.logs
=> chore: Cleanup 

CONTRIBUTION.md, LICENSE, README.md, src/components/Modal/Home/About.tsx
Updated instances "fourthclasshonours" to "foldaway"
=> chore: update instances of org name

package.json, yarn.lock
build(dep): Upgrade next from v13.1.6 to v13.4.8]
build(deps): Upgrade styled-components from 5.3.10 to 5.3.11
=> build(dep): Upgrade next from v13.1.6 to v13.4.8

src/components/Icon/index.tsx, src/components/modal/shared/Modal.tsx, src/components/modal/shared/Modal/components/CloseButton.tsx, src/components/modal/shared/Modal/index.tsx, src/components/modal/shared/ModalPortal.tsx, src/components/widget/AppLibrary/components/AppLibraryModal/components/Section.tsx, src/components/widget/AppLibrary/components/AppLibraryModal/index.tsx, src/components/widget/AppLibrary/components/styled.tsx, src/components/widget/AppLibrary/index.tsx, src/pages/_document.tsx
Issue #89 
This PR add backs the App Library Modal when the more button is clicked.
=> feat(app-library): Reintroduce App Library Modal (#89)

public/data/apps.json
This PR updates the apps.json lists.
The `smu-shortcut` segment is removed and the along with other 'dead' links
=> chore(apps): Update apps list

README.md, src/shared/components/navigation/NavHeader/components/AboutModal.tsx
This PR updates the repository URL from `foldaway/smu-shortcuts` to `alphatrl/classmaid`
=> chore: Update urls to repo

public/data/apps.json
This PR removes the apps with the `internal` type as they are not implemented yet.
* School Guides
* Boss Export
=> refactor(apps): Remove internal apps

src/pages/smu/index.tsx, src/screens/smu/components/modal/shared/Modal/components/ModalContent.tsx, src/shared/components/layouts/DefaultLayout.tsx, src/shared/components/navigation/NavHeader/index.tsx
=> fix(ios): Add padding and modal fixes for safari (#119, #120)

src/pages/smu/calendar.tsx, src/screens/smu/components/widget/AppLibrary/index.tsx, src/screens/smu/components/widget/LibraryCapacities/components/LibraryOccupancySection/components/Library.tsx, src/screens/smu/pages/calendar/components/EventsColumn/index.tsx, src/screens/smu/pages/calendar/components/InfoColumn/index.tsx, src/shared/components/layouts/DefaultLayout.tsx, src/shared/components/navigation/NavHeader/index.tsx
This PR turns the navigation bar into a sticker nav bar. Clicking on appName will redirect back to home page
=> feat: NavBar improvements

src/screens/smu/components/modal/shared/Modal/components/ModalContent.tsx, src/screens/smu/components/widget/AppLibrary/components/AppGrid.tsx, src/screens/smu/components/widget/AppLibrary/components/AppLibraryModal/components/AppItem.tsx, src/screens/smu/components/widget/AppLibrary/components/AppLibraryModal/components/Section.tsx, src/screens/smu/components/widget/AppLibrary/components/AppLibraryModal/index.tsx, src/screens/smu/components/widget/AppLibrary/constants.ts, src/shared/components/navigation/NavHeader/components/AboutModal.tsx, src/shared/components/navigation/NavHeader/components/AddToHomeModal.tsx, src/shared/hooks/useColorScheme.tsx, src/sources/smu/appsLibrary.ts
This PR brings back SMU School guide in the form of an iFrame link to an external app.
=> feat(apps): Add Taskade iFrame support 

src/screens/smu/pages/home/components/BOSSTimetableModal/index.tsx
=> feat(smu-boss-export): Show courses which are `enrolled` in (#87)

src/pages/api/smusg/getLibrariesOccupancy.ts, src/screens/smu/components/widget/LibraryCapacities/components/LibraryOccupancySection/types.ts
Issue #143 
This PR fixes an issue where the SMU libraries capacities cannot be fetched.
This is due to an updated JSON schema from the API endpoint. This PR fixes it by switching to the new API endpoint and the JSON schema which follows
=> fix(smu-libraries): Switch SMU Libraries new API key (#143)
